# x-services: &services
#   image: picbudget-backend:current
#   restart: unless-stopped
#   depends_on:
#     - db
#     - redis
#   env_file:
#     - .env

# services:
#   redis:
#     image: redis:7-alpine
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/var/lib/redis

#   celery:
#     <<: *services
#     command:
#       - ./run-celery.sh

#   db:
#     image: postgres:15-alpine
#     restart: unless-stopped
#     ports:
#       - "5432:5432"
#     env_file:
#       - .env
#     volumes:
#       - postgresql_data:/var/lib/postgresql/data

#   app:
#     <<: *services
#     command:
#       - ./run-django.sh
#     ports:
#       - "8000:8000"
#     environment:
#       PICBUDGET_SETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'
  


# services:
#   db:
#     image: postgres:15-alpine
#     restart: unless-stopped
#     ports:
#       - "5432:5432"
#     env_file:
#       - .env
#     volumes:
#       - postgresql_data:/var/lib/postgresql/data

#   redis:
#     image: redis:7-alpine 
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#     command:
#       - ./run-celery.sh

#   app:
#     build: .
#     restart: unless-stopped
#     command:
#       - ./run-gunicorn.sh
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#       - redis
#     env_file:
#       - .env
#     environment:
#       PICBUDGET_SETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

# volumes:
#   postgresql_data:
#     driver: local

#   redis_data:
#     driver: local

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=picbudget
      - POSTGRES_USER=picbudget
      - POSTGRES_PASSWORD=picbudget
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis

  app:
    image: picbudget-backend:current
    restart: unless-stopped
    command:
      - ./run-django.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PICBUDGET_SETTINGS_LOCAL_SETTINGS_PATH=local/settings.prod.py
  