services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: unless-stopped
    command: ./scripts/run-django.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/opt/project
      - ./media:/opt/project/media
    environment:
      DEBUG: "True"
      PICBUDGET_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.dev.py'

  celery:
    build: .
    command: ./scripts/run-celery.sh
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/opt/project
    environment:
      DEBUG: "True"   # Bind mount the code for live changes

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
