services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: unless-stopped
    command:
      - ./run-django.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - /var/www/media:/opt/project/media
    environment:
      PICBUDGET_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

  celery:
    build: .
    command: ./run-celery.sh
    depends_on:
      - redis
      - db
    env_file:
      - .env


volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
