services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine 
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      - ./run-celery.sh

  app:
    build: .
    restart: unless-stopped
    command:
      - ./run-gunicorn.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      PICBUDGET_SETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql_data:
    driver: local

  redis_data:
    driver: local