# Generated by Django 5.1.2 on 2024-11-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts'),
        ),
    ]
