# Generated by Django 5.1.2 on 2025-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
