import os

CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = os.getenv(
    "CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP"
)
CELERY_RESULT_EXPIRES = os.getenv("CELERY_RESULT_EXPIRES")
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE")
