# Generated by Django 5.1.2 on 2024-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='unverified', max_length=10),
        ),
    ]
